Add openssl-support

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -733,6 +733,8 @@ PROPER_LIBS
 XML2CLICK
 EXPAT_INCLUDES
 EXPAT_LIBS
+OPENSSL_INCLUDES
+OPENSSL_LIBS
 linux_makeargs
 LINUX_FIXINCLUDES_PROGRAM
 CLICKLINUX_FIXINCLUDES_PROGRAM
@@ -1425,6 +1427,7 @@ Optional Packages:
   --with-netmap           enable netmap [no]
   --with-proper[=PREFIX]  use PlanetLab Proper library (optional)
   --with-expat[=PREFIX]   locate expat XML library (optional)
+  --with-openssl[=PREFIX]   locate openssl library (optional)
 
 Some influential environment variables:
   CC          C compiler command
@@ -10008,7 +10011,7 @@ else
 
 	    	    ac_cv_endian=0
 	    cat > conftest.$ac_ext <<EOF
-#line 10011 "configure"
+#line 10014 "configure"
 #include "confdefs.h"
 #include <$endian_hdr>
 #ifdef __BYTE_ORDER
@@ -18067,6 +18070,266 @@ fi
 
 
 
+explicit_openssl=yes
+
+# Check whether --with-openssl was given.
+if test "${with_openssl+set}" = set; then
+  withval=$with_openssl; opensslprefix=$withval; if test -z "$withval" -o "$withval" = no; then opensslprefix=; fi
+else
+  opensslprefix=; explicit_openssl=yes
+fi
+
+
+if test "$opensslprefix" != no; then
+    saveflags="$CPPFLAGS"; test -n "$opensslprefix" && CPPFLAGS="$CPPFLAGS -I$opensslprefix/include"
+    if test "${ac_cv_header_openssl_opensslconf_h+set}" = set; then
+  { echo "$as_me:$LINENO: checking for openssl/opensslconf.h" >&5
+echo $ECHO_N "checking for openssl/opensslconf.h... $ECHO_C" >&6; }
+if test "${ac_cv_header_openssl_opensslconf_h+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_header_openssl_opensslconf_h" >&5
+echo "${ECHO_T}$ac_cv_header_openssl_opensslconf_h" >&6; }
+else
+  # Is the header compilable?
+{ echo "$as_me:$LINENO: checking openssl/opensslconf.h usability" >&5
+echo $ECHO_N "checking openssl/opensslconf.h usability... $ECHO_C" >&6; }
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+$ac_includes_default
+#include <openssl/opensslconf.h>
+_ACEOF
+rm -f conftest.$ac_objext
+if { (ac_try="$ac_compile"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_compile") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest.$ac_objext; then
+  ac_header_compiler=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	ac_header_compiler=no
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
+{ echo "$as_me:$LINENO: result: $ac_header_compiler" >&5
+echo "${ECHO_T}$ac_header_compiler" >&6; }
+
+# Is the header present?
+{ echo "$as_me:$LINENO: checking openssl/opensslconf.h presence" >&5
+echo $ECHO_N "checking openssl/opensslconf.h presence... $ECHO_C" >&6; }
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <openssl/opensslconf.h>
+_ACEOF
+if { (ac_try="$ac_cpp conftest.$ac_ext"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_cpp conftest.$ac_ext") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } >/dev/null && {
+	 test -z "$ac_c_preproc_warn_flag$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       }; then
+  ac_header_preproc=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+  ac_header_preproc=no
+fi
+
+rm -f conftest.err conftest.$ac_ext
+{ echo "$as_me:$LINENO: result: $ac_header_preproc" >&5
+echo "${ECHO_T}$ac_header_preproc" >&6; }
+
+# So?  What about this header?
+case $ac_header_compiler:$ac_header_preproc:$ac_c_preproc_warn_flag in
+  yes:no: )
+    { echo "$as_me:$LINENO: WARNING: openssl/opensslconf.h: accepted by the compiler, rejected by the preprocessor!" >&5
+echo "$as_me: WARNING: openssl/opensslconf.h: accepted by the compiler, rejected by the preprocessor!" >&2;}
+    { echo "$as_me:$LINENO: WARNING: openssl/opensslconf.h: proceeding with the compiler's result" >&5
+echo "$as_me: WARNING: openssl/opensslconf.h: proceeding with the compiler's result" >&2;}
+    ac_header_preproc=yes
+    ;;
+  no:yes:* )
+    { echo "$as_me:$LINENO: WARNING: openssl/opensslconf.h: present but cannot be compiled" >&5
+echo "$as_me: WARNING: openssl/opensslconf.h: present but cannot be compiled" >&2;}
+    { echo "$as_me:$LINENO: WARNING: openssl/opensslconf.h:     check for missing prerequisite headers?" >&5
+echo "$as_me: WARNING: openssl/opensslconf.h:     check for missing prerequisite headers?" >&2;}
+    { echo "$as_me:$LINENO: WARNING: openssl/opensslconf.h: see the Autoconf documentation" >&5
+echo "$as_me: WARNING: openssl/opensslconf.h: see the Autoconf documentation" >&2;}
+    { echo "$as_me:$LINENO: WARNING: openssl/opensslconf.h:     section \"Present But Cannot Be Compiled\"" >&5
+echo "$as_me: WARNING: openssl/opensslconf.h:     section \"Present But Cannot Be Compiled\"" >&2;}
+    { echo "$as_me:$LINENO: WARNING: openssl/opensslconf.h: proceeding with the preprocessor's result" >&5
+echo "$as_me: WARNING: openssl/opensslconf.h: proceeding with the preprocessor's result" >&2;}
+    { echo "$as_me:$LINENO: WARNING: openssl/opensslconf.h: in the future, the compiler will take precedence" >&5
+echo "$as_me: WARNING: openssl/opensslconf.h: in the future, the compiler will take precedence" >&2;}
+
+    ;;
+esac
+{ echo "$as_me:$LINENO: checking for openssl/opensslconf.h" >&5
+echo $ECHO_N "checking for openssl/opensslconf.h... $ECHO_C" >&6; }
+if test "${ac_cv_header_openssl_opensslconf_h+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_cv_header_openssl_opensslconf_h=$ac_header_preproc
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_header_openssl_opensslconf_h" >&5
+echo "${ECHO_T}$ac_cv_header_openssl_opensslconf_h" >&6; }
+
+fi
+if test $ac_cv_header_openssl_opensslconf_h = yes; then
+  have_openssl_h=yes
+else
+  have_openssl_h=no
+fi
+
+
+    CPPFLAGS="$saveflags"
+
+    ac_ext=c
+ac_cpp='$CPP $CPPFLAGS'
+ac_compile='$CC -c $CFLAGS $CPPFLAGS conftest.$ac_ext >&5'
+ac_link='$CC -o conftest$ac_exeext $CFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
+ac_compiler_gnu=$ac_cv_c_compiler_gnu
+
+    saveflags="$LDFLAGS"; test -n "$opensslprefix" && LDFLAGS="$LDFLAGS -L$opensslprefix/lib"
+    { echo "$as_me:$LINENO: checking for SSL_library_init in -lssl" >&5
+echo $ECHO_N "checking for SSL_library_init in -lssl... $ECHO_C" >&6; }
+if test "${ac_cv_lib_ssl_SSL_library_init+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lssl  $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+/* Override any GCC internal prototype to avoid an error.
+   Use char because int might match the return type of a GCC
+   builtin and then its argument prototype would still apply.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+char SSL_library_init ();
+int
+main ()
+{
+return SSL_library_init ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (ac_try="$ac_link"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_link") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest$ac_exeext &&
+       $as_test_x conftest$ac_exeext; then
+  ac_cv_lib_ssl_SSL_library_init=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	ac_cv_lib_ssl_SSL_library_init=no
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
+      conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_lib_ssl_SSL_library_init" >&5
+echo "${ECHO_T}$ac_cv_lib_ssl_SSL_library_init" >&6; }
+if test $ac_cv_lib_ssl_SSL_library_init = yes; then
+  have_libopenssl=yes
+else
+  have_libopenssl=no
+fi
+
+    LDFLAGS="$saveflags"
+
+    if test $have_openssl_h = yes -a $have_libopenssl = yes; then
+	cat >>confdefs.h <<\_ACEOF
+#define HAVE_OPENSSL 1
+_ACEOF
+
+	test -n "$opensslprefix" && OPENSSL_INCLUDES="-I$opensslprefix/include" && OPENSSL_LIBS="-L$opensslprefix/lib"
+	OPENSSL_LIBS="$OPENSSL_LIBS -lssl -lcrypto"
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_OPENSSL 1
+_ACEOF
+
+	LIBS="$LIBS $OPENSSL_LIBS"
+    elif test $explicit_openssl = yes; then
+	OPENSSL_INCLUDES= OPENSSL_LIBS=
+	{ { echo "$as_me:$LINENO: error:
+=========================================
+
+You explicitly specified --with-openssl, but the openssl headers and/or libraries
+are not where you said they would be.  Run again supplying --without-openssl
+or --with-openssl=PREFIX.
+
+=========================================" >&5
+echo "$as_me: error:
+=========================================
+
+You explicitly specified --with-openssl, but the openssl headers and/or libraries
+are not where you said they would be.  Run again supplying --without-openssl
+or --with-openssl=PREFIX.
+
+=========================================" >&2;}
+   { (exit 1); exit 1; }; }
+    fi
+fi
+
+
+
+
 
 if test $ac_have_linux_kernel = y; then
 
@@ -21680,6 +21943,8 @@ PROPER_LIBS!$PROPER_LIBS$ac_delim
 XML2CLICK!$XML2CLICK$ac_delim
 EXPAT_INCLUDES!$EXPAT_INCLUDES$ac_delim
 EXPAT_LIBS!$EXPAT_LIBS$ac_delim
+OPENSSL_INCLUDES!$OPENSSL_INCLUDES$ac_delim
+OPENSSL_LIBS!$OPENSSL_LIBS$ac_delim
 linux_makeargs!$linux_makeargs$ac_delim
 LINUX_FIXINCLUDES_PROGRAM!$LINUX_FIXINCLUDES_PROGRAM$ac_delim
 CLICKLINUX_FIXINCLUDES_PROGRAM!$CLICKLINUX_FIXINCLUDES_PROGRAM$ac_delim
@@ -21717,7 +21982,7 @@ provisions!$provisions$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 58; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 60; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
