linuxmodule: correctly zero out packet txflags in linux 2.6.32
Signed-off-by: Cliff Frey <cliff@meraki.com>

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -19764,6 +19764,89 @@ _ACEOF
 
     fi
 
+    { echo "$as_me:$LINENO: checking whether skb_shinfo has tx_flags.flags" >&5
+echo $ECHO_N "checking whether skb_shinfo has tx_flags.flags... $ECHO_C" >&6; }
+if test "${ac_cv_linuxmodule_skb_shinfo_tx_flags_union+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_ext=c
+ac_cpp='$CPP $CPPFLAGS'
+ac_compile='$CC -c $CFLAGS $CPPFLAGS conftest.$ac_ext >&5'
+ac_link='$CC -o conftest$ac_exeext $CFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
+ac_compiler_gnu=$ac_cv_c_compiler_gnu
+
+	cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#if HAVE_LINUXMODULE_2_6
+# define KBUILD_STR(s)		#s
+# define KBUILD_BASENAME	KBUILD_STR(click)
+# define KBUILD_MODNAME		KBUILD_STR(click)
+#endif
+#define new linux_new
+#define this linux_this
+#define delete linux_delete
+#define class linux_class
+#define virtual linux_virtual
+#define typename linux_typename
+#define private linux_private
+#define protected linux_protected
+#define public linux_public
+#define namespace linux_namespace
+#define false linux_false
+#define true linux_true
+#define CLICK_CXX_PROTECTED 1
+$linux_autoconf_include
+#include <asm/types.h>
+#include <linux/skbuff.h>
+int
+main ()
+{
+extern struct sk_buff *s; skb_shinfo(s)->tx_flags.flags = 0;
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (ac_try="$ac_compile"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_compile") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest.$ac_objext; then
+  ac_cv_linuxmodule_skb_shinfo_tx_flags_union=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	ac_cv_linuxmodule_skb_shinfo_tx_flags_union=no
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_linuxmodule_skb_shinfo_tx_flags_union" >&5
+echo "${ECHO_T}$ac_cv_linuxmodule_skb_shinfo_tx_flags_union" >&6; }
+    if test $ac_cv_linuxmodule_skb_shinfo_tx_flags_union = yes; then
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_LINUX_SKB_SHINFO_TX_FLAGS_UNION 1
+_ACEOF
+
+    fi
+
     { echo "$as_me:$LINENO: checking for device polling kernel extension" >&5
 echo $ECHO_N "checking for device polling kernel extension... $ECHO_C" >&6; }
 if test "${ac_cv_linuxmodule_net_device_polling+set}" = set; then
